<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class PostManager {

	/**
	 * 
	 * @var string
	 * @access private
	 */

	private $_db;

	/**
	 * @access public
	 * @param PDO $db
	 * @return void
	 */

	public function __construct($db)
  	{
    	$this->setDb($db);
  	}

	/**
	 * @access public
	 * @param objet $post
	 * @return void
	 */

	public function addPost(Post $post)
	{
		$db = $this->dbConnect();
		$q = $db->prepare('INSERT INTO posts(image, title, text, date, tag, status) VALUES(:image, :title, :text, :date, :tag, :status)');

		$q->bindValue(':image', $post->image());
		$q->bindValue(':title', $post->title());
		$q->bindValue(':text', $post->text());
		$q->bindValue(':date', $post->date());
		$q->bindValue(':tag', $post->tag());
		$q->bindValue(':status', $post->status(), PDO::PARAM_INT);

		$q->execute();
	}

	/**
	 * @access public
	 * @return array
	 */

	public final  function getPosts() {
		$listPosts = [];

		$db = $this->dbConnect();
		$q = $db->query('SELECT id, image, title, text, date, tag, status FROM posts ORDER BY date DESC');

		while ($data = $q->fetch(PDO::FETCH_ASSOC))
		{
			$listPosts[] = new Post($data);
		}

		return $listPosts;
	}


	/**
	 * @access public
	 * @param int $postId 
	 * @return objet
	 */

	public final  function getPost($postId) {
		if(!is_int($postId))
		{
			trigger_error('the $postId should be a int type', E_USER_WARNING);
		  	return;
		}
		else {
			$db = $this->dbConnect();
			$q = $db->query('SELECT id, image, title, text, date, tag FROM posts WHERE id = '.$postid);

			$data = $q->fetch(PDO::FECTH_ASSOC);

			return new Comment($data);
		}
	}


	/**
	 * @access public
	 * @param int $postId 
	 * @return objet
	 */

	public final  function updatePost(Post $post) {

		$db = $this->dbConnect();
		$q = $db->prepare('UPDATE posts SET image = :image, title = :title, text = :text; date = :date, tag = :tag, status = :status WHERE id = :id');

		$q->bindValue(':id', $post->id(), PDO::PARAM_INT);
		$q->bindValue(':image', $post->image());
		$q->bindValue(':title', $post->title());
		$q->bindValue(':text', $post->text());
		$q->bindValue(':date', $post->date());
		$q->bindValue(':tag', $post->tag());
		$q->bindValue(':status', $post->status(), PDO::PARAM_INT);

		$q->execute();
	}


	/**
	 * @access public
	 * @param objet $post 
	 * @return void
	 */

	public final  function deletePost(Post $post) {
		$this->_db->exec('DELETE FROM posts WHERE id = '.$post->id());
	}

	/**
	 * @access public
	 * @param PDO $db
	 * @return void
	 */

	public function setDb(PDO $db)
	{
		$this->_db = $db;
	}

	/**
	 * @access public
	 * @param
	 * @return PDO $db
	 */

	public function dbConnect()
	{
		try
		{
			$db = $this->_db;
			return $db;
		}
		catch(Exception $e)
		{
			die('Erreur : '.$e->getMessage());
		}
	}

	public function showText()
	{
		echo 'montre le texte';
	}

}
?>